### ISSUE TITLE
docker-compose up --build -d | Error groupadd: invalid group ID 'vrising'

### ISSUE THREAD

**Issue by JotunJosh** [theCrius/v-rising#1]
After running the `docker-compose up --build -d` i got the following error:

```
groupadd: invalid group ID 'vrising'
The command '/bin/bash -o pipefail -c mkdir -p $INSTALL_DIR &&     groupadd -g $GID vrising &&     useradd -m -s /bin/false -u $UID -g $GID vrising &&     mkdir -p $INSTALL_DIR &&     chown -R vrising:vrising ${INSTALL_DIR}' returned a non-zero code: 3
ERROR: Service 'vrising' failed to build : Build failed
```

**Comment by JotunJosh** [comment]
Oh and on these two commands i get not really an error but my terminal says the value is read only 

```
export UID=$(id -u)
export UID=$(id -g)
```

**Comment by theCrius** [comment]
> Oh and on these two commands i get not really an error but my terminal says the value is read only
> 
> ```
> export UID=$(id -u)
> export UID=$(id -g)
> ```

This is fine, it's just the system warning you have already an UID environment variable and it's non-writable as it should be. I included the command anyway as a way to ensure that it's there.

> After running the `docker-compose up --build -d` i got the following error:
> 
> ```
> groupadd: invalid group ID 'vrising'
> The command '/bin/bash -o pipefail -c mkdir -p $INSTALL_DIR &&     groupadd -g $GID vrising &&     useradd -m -s /bin/false -u $UID -g $GID vrising &&     mkdir -p $INSTALL_DIR &&     chown -R vrising:vrising ${INSTALL_DIR}' returned a non-zero code: 3
> ERROR: Service 'vrising' failed to build : Build failed
> ```

From your host, can you run the command `id -g`? You should get a number back, something like this:
![image](https://user-images.githubusercontent.com/2202141/172422521-89a2ad22-76c9-4b30-ba2b-a20bb4a2ddc3.png)

**Comment by theCrius** [comment]
Ah! @lopio1234 my bad! I've noticed the issue! It's a typo in the readme.

Instead of:
```
export UID=$(id -u)
export UID=$(id -g)
```

It should have been:
```
export UID=$(id -u)
export GID=$(id -g)
```

I'll fix the readme!
